# Global parameters for create model node.
algorithm: ""
k_bests: [1, 2, 3, 4, 5]
n_splits: 7
transform_target: True
scoring:
  RMSE: "neg_root_mean_squared_error"
  MAE: "neg_mean_absolute_error"
  R2: "r2"

## Model hyperparameters #
##########################
mars_hypms:
  max_degree: [3, 4, 5]
  allow_linear: [False, True]
  penalty: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
