# Number of best features (k best features)
algorithm: ""
k_bests: [1, 2]
n_splits: 7

## Model hyperparameters #
##########################
mars:
  max_degree: [3, 4, 5]
  allow_linear: [False, True]
  penalty: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
