#############################################################
## Global parameters for all pipelines
#############################################################

# Wind Farm identification, by default empty value.
wf: ""

# data persistence
folder:
  raw: "./data/01_raw/"
  int: "./data/02_intermediate/"
  pri: "./data/03_primary/"
  fea: "./data/04_feature/"
  minp: "./data/05_model_input/"
  mdl: "./data/06_models/"
  mout: "./data/07_model_output/"
  rep: "./data/08_reporting/"
  cnr:
    primary: "./data/CNR/01_primary_data/"
    prepared: "./data/CNR/02_prepared_data/"
    models: "./data/CNR/03_models/"
    predictions: "./data/CNR/04_predictions/"
