#############################################################
## Global parameters
#############################################################

# data persistence
folder:
  raw: "./data/01_raw/"
  int: "./data/02_intermediate/"
  pri: "./data/03_primary/"
  fea: "./data/04_feature/"
  minp: "./data/05_model_iput/"
  mdl: "./data/06_models/"
  mout: "./data/07_model_output/"
  rep: "./data/08_reporting/"
