
# New columns to be added throught node 'add_new_columns'.
new_cols:
  [
    "NWP1_U",
    "NWP1_V",
    "NWP1_T",
    "NWP2_U",
    "NWP2_V",
    "NWP3_U",
    "NWP3_V",
    "NWP3_T",
    "NWP4_U",
    "NWP4_V",
    "NWP4_CLCT",
  ]

# Columns that need interpolation for missing values.
cols_to_interpol:
  ["NWP2_U", "NWP2_V", "NWP3_U", "NWP3_V", "NWP3_T", "NWP4_CLCT"]

# Figure identification to use when saving a figure from _save_fig function.
fig_id: "outliers"

# The date from we want to split the X and y data sets into train/test sets.
# split_date: "2019-01-14 23:00:00"  # day
# split_date: "2019-01-08 23:00:00" # week
split_date: "2018-12-14 23:00:00" # month

# Outliers detection parameters
WF1:
  top_frac_max: 0.99
  sparse_bin_width: 0.1
  frac_std: 0.9
  threshold_type: "scalar"
  bottom_max: 5.5
WF2:
  top_frac_max: 0.97
  sparse_bin_width: 0.15
  frac_std: 0.8
  threshold_type: "scalar"
  bottom_max: 5.5
WF3:
  top_frac_max: 0.97
  sparse_bin_width: 0.1
  frac_std: 0.8
  threshold_type: "scalar"
  bottom_max: 5.5
WF4:
  top_frac_max: 0.97
  sparse_bin_width: 0.1
  frac_std: 0.95
  threshold_type: "scalar"
  bottom_max: 5.3
WF5:
  top_frac_max: 0.97
  sparse_bin_width: 0.1
  frac_std: 0.9
  threshold_type: "scalar"
  bottom_max: 5.0
WF6:
  top_frac_max: 0.97
  sparse_bin_width: 0.05
  frac_std: 1.0
  threshold_type: "std"
  bottom_max: 5.0
